import json

with open('P4_parte_1_GANs.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

def code_cell(source):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source
    }

# =====================================================================
# EJERCICIO 1: CIFAR-10
# =====================================================================
ej1_code = (
    "# Ejercicio 1: CIFAR-10 en lugar de MNIST\n"
    "import os\n"
    "os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1'\n"
    "import tensorflow as tf\n"
    "import numpy as np\n"
    "from keras.datasets import cifar10\n"
    "from keras.layers import Input, Dense, Reshape, Flatten, BatchNormalization, LeakyReLU\n"
    "from keras.models import Sequential\n"
    "from keras.optimizers import Adam\n"
    "from tqdm.notebook import tqdm\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "# --- Datos CIFAR-10 ---\n"
    "(X_train_c, _), (_, _) = cifar10.load_data()\n"
    "X_train_c = X_train_c.astype(np.float32) / 255.0 * 2.0 - 1.0  # normalizar a [-1, 1]\n"
    "in_shape_c = X_train_c.shape[1:]  # (32, 32, 3)\n"
    "latent_dim = 100\n"
    "\n"
    "# --- Optimizadores ---\n"
    "opt_gen_c = Adam(learning_rate=2e-4, beta_1=0.5, weight_decay=8e-8)\n"
    "opt_dis_c = Adam(learning_rate=2e-4, beta_1=0.5, weight_decay=8e-8)\n"
    "\n"
    "# --- Generador ---\n"
    "model_gen_c = Sequential(name='generator_cifar')\n"
    "model_gen_c.add(Input((latent_dim,)))\n"
    "model_gen_c.add(Dense(256));  model_gen_c.add(LeakyReLU(negative_slope=0.2)); model_gen_c.add(BatchNormalization(momentum=0.8))\n"
    "model_gen_c.add(Dense(512));  model_gen_c.add(LeakyReLU(negative_slope=0.2)); model_gen_c.add(BatchNormalization(momentum=0.8))\n"
    "model_gen_c.add(Dense(1024)); model_gen_c.add(LeakyReLU(negative_slope=0.2)); model_gen_c.add(BatchNormalization(momentum=0.8))\n"
    "model_gen_c.add(Dense(int(np.prod(in_shape_c)), activation='tanh'))\n"
    "model_gen_c.add(Reshape(in_shape_c))\n"
    "model_gen_c.summary()\n"
    "\n"
    "# --- Discriminador (mas ancho para manejar 32x32x3) ---\n"
    "model_disc_c = Sequential(name='discriminator_cifar')\n"
    "model_disc_c.add(Input(in_shape_c))\n"
    "model_disc_c.add(Flatten())\n"
    "model_disc_c.add(Dense(512));  model_disc_c.add(LeakyReLU(negative_slope=0.2))\n"
    "model_disc_c.add(Dense(256));  model_disc_c.add(LeakyReLU(negative_slope=0.2))\n"
    "model_disc_c.add(Dense(1, activation='sigmoid'))\n"
    "model_disc_c.summary()\n"
    "model_disc_c.compile(loss='binary_crossentropy', optimizer=opt_dis_c, metrics=['accuracy'])\n"
    "\n"
    "# --- Modelo combinado ---\n"
    "model_disc_c.trainable = False\n"
    "model_gan_c = Sequential(name='gan_cifar')\n"
    "model_gan_c.add(model_gen_c); model_gan_c.add(model_disc_c)\n"
    "model_gan_c.compile(loss='binary_crossentropy', optimizer=opt_gen_c)\n"
    "model_disc_c.trainable = True\n"
    "\n"
    "# --- Entrenamiento ---\n"
    "DD_loss_c, GG_loss_c = [], []\n"
    "n_train_c = 10000; epochs_c = 50; batch_size_c = 128\n"
    "dataset_c = tf.data.Dataset.from_tensor_slices(X_train_c).\\\n"
    "    shuffle(len(X_train_c), reshuffle_each_iteration=True).batch(batch_size_c)\n"
    "pb = tqdm(range(epochs_c), desc='Training CIFAR-10 GAN')\n"
    "for epoch in pb:\n"
    "    g_loss, d_loss, d_acc = 0.0, 0.0, 0.0\n"
    "    for x_real in dataset_c.take(n_train_c // batch_size_c):\n"
    "        bs = x_real.shape[0]\n"
    "        x_fake = model_gen_c(tf.random.normal((bs, latent_dim)))\n"
    "        xx = tf.concat([x_real, x_fake], axis=0)\n"
    "        yy = tf.concat([tf.ones((bs, 1)), tf.zeros((bs, 1))], axis=0)\n"
    "        model_disc_c.trainable = True\n"
    "        dm = model_disc_c.train_on_batch(xx, yy)\n"
    "        d_loss += dm[0]; d_acc += dm[1]\n"
    "        model_disc_c.trainable = False\n"
    "        g_loss += model_gan_c.train_on_batch(tf.random.normal((2*bs, latent_dim)), tf.ones((2*bs, 1)))\n"
    "    nb_c = n_train_c // batch_size_c\n"
    "    d_loss /= nb_c; d_acc /= nb_c; g_loss /= nb_c\n"
    "    pb.set_description(f'CIFAR gen={g_loss:.4f} disc={d_loss:.4f} acc={d_acc:.4f}')\n"
    "    DD_loss_c.append(d_loss); GG_loss_c.append(g_loss)\n"
    "\n"
    "plt.plot(DD_loss_c, label='Discriminador'); plt.plot(GG_loss_c, label='Generador')\n"
    "plt.legend(); plt.title('CIFAR-10 GAN - Curvas de aprendizaje'); plt.show()\n"
    "\n"
    "# Visualizar imagenes generadas\n"
    "gen_noise_c = np.random.normal(0, 1, (10, latent_dim))\n"
    "synthetic_c = model_gen_c(gen_noise_c).numpy()\n"
    "synthetic_c = (synthetic_c + 1.0) / 2.0  # denormalizar a [0,1]\n"
    "for i in range(5):\n"
    "    plt.subplot(2, 5, i+1);   plt.imshow(synthetic_c[i]);   plt.axis('off')\n"
    "    plt.subplot(2, 5, 5+i+1); plt.imshow(synthetic_c[2*i]); plt.axis('off')\n"
    "plt.suptitle('Imagenes CIFAR-10 generadas'); plt.tight_layout(); plt.show()\n"
)

# =====================================================================
# EJERCICIO 2: cGAN con etiquetas
# =====================================================================
ej2_code = (
    "# Ejercicio 2: Generar con etiquetas - GAN Condicional (cGAN) sobre MNIST\n"
    "from keras.datasets import mnist\n"
    "from keras.layers import Input, Dense, Reshape, Flatten, BatchNormalization, LeakyReLU, Concatenate\n"
    "from keras.models import Model\n"
    "from keras.optimizers import Adam\n"
    "import tensorflow as tf\n"
    "import numpy as np\n"
    "from tqdm.notebook import tqdm\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "# --- Parametros ---\n"
    "latent_cgan = 100; num_classes = 10\n"
    "img_shape_cg = (28, 28, 1); img_flat_cg = int(28*28*1)\n"
    "\n"
    "# --- Datos ---\n"
    "(X_tr_cg, y_tr_cg), (_, _) = mnist.load_data()\n"
    "X_tr_cg = X_tr_cg.astype(np.float32) / 255.0 * 2.0 - 1.0\n"
    "X_tr_cg = np.expand_dims(X_tr_cg, -1)\n"
    "y_onehot = np.eye(num_classes)[y_tr_cg]  # (60000, 10)\n"
    "\n"
    "# --- Generador condicional ---\n"
    "noise_in   = Input(shape=(latent_cgan,))\n"
    "label_in_g = Input(shape=(num_classes,))\n"
    "x_g = Concatenate()([noise_in, label_in_g])\n"
    "x_g = Dense(256)(x_g);  x_g = LeakyReLU(0.2)(x_g); x_g = BatchNormalization(momentum=0.8)(x_g)\n"
    "x_g = Dense(512)(x_g);  x_g = LeakyReLU(0.2)(x_g); x_g = BatchNormalization(momentum=0.8)(x_g)\n"
    "x_g = Dense(1024)(x_g); x_g = LeakyReLU(0.2)(x_g); x_g = BatchNormalization(momentum=0.8)(x_g)\n"
    "x_g = Dense(img_flat_cg, activation='tanh')(x_g)\n"
    "img_out = Reshape(img_shape_cg)(x_g)\n"
    "cgen = Model([noise_in, label_in_g], img_out, name='cgan_generator')\n"
    "cgen.summary()\n"
    "\n"
    "# --- Discriminador condicional ---\n"
    "img_in    = Input(shape=img_shape_cg)\n"
    "label_in_d = Input(shape=(num_classes,))\n"
    "x_d = Flatten()(img_in)\n"
    "x_d = Concatenate()([x_d, label_in_d])\n"
    "x_d = Dense(512)(x_d); x_d = LeakyReLU(0.2)(x_d)\n"
    "x_d = Dense(256)(x_d); x_d = LeakyReLU(0.2)(x_d)\n"
    "validity = Dense(1, activation='sigmoid')(x_d)\n"
    "cdisc = Model([img_in, label_in_d], validity, name='cgan_discriminator')\n"
    "cdisc.summary()\n"
    "cdisc.compile(loss='binary_crossentropy', optimizer=Adam(2e-4, beta_1=0.5), metrics=['accuracy'])\n"
    "\n"
    "# --- Modelo combinado ---\n"
    "cdisc.trainable = False\n"
    "noise_comb = Input(shape=(latent_cgan,))\n"
    "label_comb = Input(shape=(num_classes,))\n"
    "cgan_model = Model([noise_comb, label_comb],\n"
    "                   cdisc([cgen([noise_comb, label_comb]), label_comb]),\n"
    "                   name='cgan_combined')\n"
    "cgan_model.compile(loss='binary_crossentropy', optimizer=Adam(2e-4, beta_1=0.5))\n"
    "cdisc.trainable = True\n"
    "\n"
    "# --- Entrenamiento ---\n"
    "n_tr_cg = 20000; ep_cg = 100; bs_cg = 128\n"
    "DD_cg, GG_cg = [], []\n"
    "pb = tqdm(range(ep_cg), desc='Training cGAN')\n"
    "for epoch in pb:\n"
    "    g_l, d_l, d_a = 0.0, 0.0, 0.0\n"
    "    n_b = n_tr_cg // bs_cg\n"
    "    for _ in range(n_b):\n"
    "        idx = np.random.choice(len(X_tr_cg), bs_cg, replace=False)\n"
    "        imgs_real = X_tr_cg[idx]; labels_real = y_onehot[idx]\n"
    "        fake_labels = np.eye(num_classes)[np.random.randint(0, num_classes, bs_cg)]\n"
    "        imgs_fake = cgen.predict([np.random.normal(0,1,(bs_cg, latent_cgan)), fake_labels], verbose=0)\n"
    "        cdisc.trainable = True\n"
    "        dr = cdisc.train_on_batch([imgs_real, labels_real], np.ones((bs_cg,1)))\n"
    "        df = cdisc.train_on_batch([imgs_fake, fake_labels], np.zeros((bs_cg,1)))\n"
    "        d_l += 0.5*(dr[0]+df[0]); d_a += 0.5*(dr[1]+df[1])\n"
    "        cdisc.trainable = False\n"
    "        gen_lab = np.eye(num_classes)[np.random.randint(0, num_classes, bs_cg)]\n"
    "        g_l += cgan_model.train_on_batch(\n"
    "            [np.random.normal(0,1,(bs_cg, latent_cgan)), gen_lab], np.ones((bs_cg,1)))\n"
    "    d_l /= n_b; d_a /= n_b; g_l /= n_b\n"
    "    pb.set_description(f'cGAN gen={g_l:.4f} disc={d_l:.4f} acc={d_a:.4f}')\n"
    "    DD_cg.append(d_l); GG_cg.append(g_l)\n"
    "\n"
    "plt.plot(DD_cg, label='Discriminador'); plt.plot(GG_cg, label='Generador')\n"
    "plt.legend(); plt.title('cGAN - Curvas de aprendizaje'); plt.show()\n"
    "\n"
    "# Visualizar: un digito por clase\n"
    "noise_vis = np.random.normal(0, 1, (num_classes, latent_cgan))\n"
    "gen_vis = cgen.predict([noise_vis, np.eye(num_classes)], verbose=0)\n"
    "gen_vis = (gen_vis + 1.0) / 2.0\n"
    "fig, axes = plt.subplots(1, num_classes, figsize=(20, 2))\n"
    "for i in range(num_classes):\n"
    "    axes[i].imshow(gen_vis[i,:,:,0], cmap='gray'); axes[i].set_title(str(i)); axes[i].axis('off')\n"
    "plt.suptitle('cGAN: un digito por clase'); plt.tight_layout(); plt.show()\n"
)

# =====================================================================
# EJERCICIO 3: DCGAN con capas convolucionales
# =====================================================================
ej3_code = (
    "# Ejercicio 3: Capas convolucionales - DCGAN sobre MNIST\n"
    "from keras.datasets import mnist\n"
    "from keras.layers import (Input, Dense, Reshape, Flatten, BatchNormalization,\n"
    "                           LeakyReLU, Conv2D, Conv2DTranspose)\n"
    "from keras.models import Sequential\n"
    "from keras.optimizers import Adam\n"
    "import tensorflow as tf\n"
    "import numpy as np\n"
    "from tqdm.notebook import tqdm\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "# --- Datos MNIST ---\n"
    "(X_tr_dc, _), (_, _) = mnist.load_data()\n"
    "X_tr_dc = X_tr_dc.astype(np.float32) / 255.0 * 2.0 - 1.0\n"
    "X_tr_dc = np.expand_dims(X_tr_dc, -1)  # (60000, 28, 28, 1)\n"
    "latent_dc = 100\n"
    "\n"
    "# --- Generador: noise -> 7x7x128 -> 14x14x64 -> 28x28x1 ---\n"
    "dcgen = Sequential(name='dcgan_generator')\n"
    "dcgen.add(Input((latent_dc,)))\n"
    "dcgen.add(Dense(7 * 7 * 128))\n"
    "dcgen.add(Reshape((7, 7, 128)))\n"
    "dcgen.add(BatchNormalization(momentum=0.8))\n"
    "dcgen.add(Conv2DTranspose(64, kernel_size=4, strides=2, padding='same'))\n"
    "dcgen.add(LeakyReLU(0.2))\n"
    "dcgen.add(BatchNormalization(momentum=0.8))\n"
    "dcgen.add(Conv2DTranspose(32, kernel_size=4, strides=2, padding='same'))\n"
    "dcgen.add(LeakyReLU(0.2))\n"
    "dcgen.add(BatchNormalization(momentum=0.8))\n"
    "dcgen.add(Conv2D(1, kernel_size=3, padding='same', activation='tanh'))\n"
    "dcgen.summary()\n"
    "\n"
    "# --- Discriminador convolucional ---\n"
    "dcdisc = Sequential(name='dcgan_discriminator')\n"
    "dcdisc.add(Input((28, 28, 1)))\n"
    "dcdisc.add(Conv2D(32,  kernel_size=3, strides=2, padding='same')); dcdisc.add(LeakyReLU(0.2))\n"
    "dcdisc.add(Conv2D(64,  kernel_size=3, strides=2, padding='same')); dcdisc.add(LeakyReLU(0.2))\n"
    "dcdisc.add(Conv2D(128, kernel_size=3, strides=1, padding='same')); dcdisc.add(LeakyReLU(0.2))\n"
    "dcdisc.add(Flatten())\n"
    "dcdisc.add(Dense(1, activation='sigmoid'))\n"
    "dcdisc.summary()\n"
    "dcdisc.compile(loss='binary_crossentropy',\n"
    "               optimizer=Adam(2e-4, beta_1=0.5, weight_decay=8e-8),\n"
    "               metrics=['accuracy'])\n"
    "\n"
    "# --- Modelo combinado ---\n"
    "dcdisc.trainable = False\n"
    "dcgan = Sequential(name='dcgan_combined')\n"
    "dcgan.add(dcgen); dcgan.add(dcdisc)\n"
    "dcgan.compile(loss='binary_crossentropy', optimizer=Adam(2e-4, beta_1=0.5, weight_decay=8e-8))\n"
    "dcdisc.trainable = True\n"
    "\n"
    "# --- Entrenamiento ---\n"
    "n_tr_dc = 20000; ep_dc = 100; bs_dc = 128\n"
    "DD_dc, GG_dc = [], []\n"
    "ds_dc = tf.data.Dataset.from_tensor_slices(X_tr_dc).\\\n"
    "    shuffle(len(X_tr_dc), reshuffle_each_iteration=True).batch(bs_dc)\n"
    "pb = tqdm(range(ep_dc), desc='Training DCGAN')\n"
    "for epoch in pb:\n"
    "    g_l, d_l, d_a = 0.0, 0.0, 0.0\n"
    "    for x_real in ds_dc.take(n_tr_dc // bs_dc):\n"
    "        bs = x_real.shape[0]\n"
    "        x_fake = dcgen(tf.random.normal((bs, latent_dc)))\n"
    "        xx = tf.concat([x_real, x_fake], axis=0)\n"
    "        yy = tf.concat([tf.ones((bs,1)), tf.zeros((bs,1))], axis=0)\n"
    "        dcdisc.trainable = True\n"
    "        dm = dcdisc.train_on_batch(xx, yy)\n"
    "        d_l += dm[0]; d_a += dm[1]\n"
    "        dcdisc.trainable = False\n"
    "        g_l += dcgan.train_on_batch(tf.random.normal((2*bs, latent_dc)), tf.ones((2*bs,1)))\n"
    "    n_b = n_tr_dc // bs_dc\n"
    "    d_l /= n_b; d_a /= n_b; g_l /= n_b\n"
    "    pb.set_description(f'DCGAN gen={g_l:.4f} disc={d_l:.4f} acc={d_a:.4f}')\n"
    "    DD_dc.append(d_l); GG_dc.append(g_l)\n"
    "\n"
    "plt.plot(DD_dc, label='Discriminador'); plt.plot(GG_dc, label='Generador')\n"
    "plt.legend(); plt.title('DCGAN - Curvas de aprendizaje'); plt.show()\n"
    "\n"
    "imgs_dc = dcgen(np.random.normal(0,1,(10, latent_dc))).numpy()\n"
    "for i in range(5):\n"
    "    plt.subplot(2,5,i+1);   plt.imshow(imgs_dc[i,:,:,0],   cmap='gray'); plt.axis('off')\n"
    "    plt.subplot(2,5,5+i+1); plt.imshow(imgs_dc[2*i,:,:,0], cmap='gray'); plt.axis('off')\n"
    "plt.suptitle('DCGAN: imagenes con capas convolucionales'); plt.tight_layout(); plt.show()\n"
)

# =====================================================================
# EJERCICIO EXTRA 1: Balanceo dinamico
# =====================================================================
ej_extra1_code = (
    "# Ejercicio EXTRA 1: Balanceo dinamico de entrenamiento segun loss previo\n"
    "#\n"
    "# Regla: si disc. tiene loss bajo (aprende mucho) => reduce sus batches.\n"
    "# Se reparte como ratio = d_loss / (d_loss + g_loss), entre [0.2, 0.8].\n"
    "# El discriminador recibe base_batches * ratio batches;\n"
    "# el generador recibe base_batches * (1 - ratio).\n"
    "from keras.datasets import mnist\n"
    "from keras.layers import Input, Dense, Reshape, Flatten, BatchNormalization, LeakyReLU\n"
    "from keras.models import Sequential\n"
    "from keras.optimizers import Adam\n"
    "import tensorflow as tf\n"
    "import numpy as np\n"
    "from tqdm.notebook import tqdm\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "# --- Datos ---\n"
    "(X_tr_ex, _), (_, _) = mnist.load_data()\n"
    "X_tr_ex = X_tr_ex.astype(np.float32) / 255.0 * 2.0 - 1.0\n"
    "X_tr_ex = np.expand_dims(X_tr_ex, -1)\n"
    "in_sh_ex = X_tr_ex.shape[1:]; lat_ex = 100\n"
    "\n"
    "# --- Modelos (misma arquitectura que el prelab) ---\n"
    "gen_ex = Sequential(name='gen_ex1')\n"
    "gen_ex.add(Input((lat_ex,)))\n"
    "gen_ex.add(Dense(256));  gen_ex.add(LeakyReLU(0.2)); gen_ex.add(BatchNormalization(0.8))\n"
    "gen_ex.add(Dense(512));  gen_ex.add(LeakyReLU(0.2)); gen_ex.add(BatchNormalization(0.8))\n"
    "gen_ex.add(Dense(1024)); gen_ex.add(LeakyReLU(0.2)); gen_ex.add(BatchNormalization(0.8))\n"
    "gen_ex.add(Dense(int(np.prod(in_sh_ex)), activation='tanh'))\n"
    "gen_ex.add(Reshape(in_sh_ex))\n"
    "\n"
    "dis_ex = Sequential(name='dis_ex1')\n"
    "dis_ex.add(Input(in_sh_ex)); dis_ex.add(Flatten())\n"
    "dis_ex.add(Dense(128)); dis_ex.add(LeakyReLU(0.2))\n"
    "dis_ex.add(Dense(64));  dis_ex.add(LeakyReLU(0.2))\n"
    "dis_ex.add(Dense(1, activation='sigmoid'))\n"
    "dis_ex.compile(loss='binary_crossentropy',\n"
    "               optimizer=Adam(2e-4, beta_1=0.5, weight_decay=8e-8), metrics=['accuracy'])\n"
    "\n"
    "dis_ex.trainable = False\n"
    "gan_ex = Sequential(name='gan_ex1')\n"
    "gan_ex.add(gen_ex); gan_ex.add(dis_ex)\n"
    "gan_ex.compile(loss='binary_crossentropy', optimizer=Adam(2e-4, beta_1=0.5, weight_decay=8e-8))\n"
    "dis_ex.trainable = True\n"
    "\n"
    "# --- Entrenamiento con balanceo dinamico ---\n"
    "n_samples_ex = 20000; ep_ex = 100; bs_ex = 128\n"
    "base_batches = n_samples_ex // bs_ex\n"
    "DD_ex, GG_ex = [], []\n"
    "prev_d = 1.0; prev_g = 1.0\n"
    "\n"
    "ds_ex = (tf.data.Dataset.from_tensor_slices(X_tr_ex)\n"
    "         .shuffle(len(X_tr_ex), reshuffle_each_iteration=True)\n"
    "         .batch(bs_ex).repeat())\n"
    "it_ex = iter(ds_ex)\n"
    "\n"
    "pb = tqdm(range(ep_ex), desc='GAN Balanceo Dinamico')\n"
    "for epoch in pb:\n"
    "    ratio   = float(np.clip(prev_d / (prev_d + prev_g + 1e-8), 0.2, 0.8))\n"
    "    n_d_bat = max(1, int(base_batches * ratio))\n"
    "    n_g_bat = max(1, int(base_batches * (1.0 - ratio)))\n"
    "    g_l, d_l, d_a = 0.0, 0.0, 0.0\n"
    "\n"
    "    # Entrenar discriminador n_d_bat batches\n"
    "    dis_ex.trainable = True\n"
    "    for _ in range(n_d_bat):\n"
    "        xr = next(it_ex); b = xr.shape[0]\n"
    "        xf = gen_ex(tf.random.normal((b, lat_ex)))\n"
    "        dm = dis_ex.train_on_batch(\n"
    "            tf.concat([xr, xf], 0), tf.concat([tf.ones((b,1)), tf.zeros((b,1))], 0))\n"
    "        d_l += dm[0]; d_a += dm[1]\n"
    "    d_l /= n_d_bat; d_a /= n_d_bat\n"
    "\n"
    "    # Entrenar generador n_g_bat batches\n"
    "    dis_ex.trainable = False\n"
    "    for _ in range(n_g_bat):\n"
    "        g_l += gan_ex.train_on_batch(tf.random.normal((bs_ex, lat_ex)), tf.ones((bs_ex,1)))\n"
    "    g_l /= n_g_bat\n"
    "\n"
    "    prev_d = d_l; prev_g = g_l\n"
    "    pb.set_description(\n"
    "        f'd_bat={n_d_bat} g_bat={n_g_bat} | gen={g_l:.4f} disc={d_l:.4f} acc={d_a:.4f}')\n"
    "    DD_ex.append(d_l); GG_ex.append(g_l)\n"
    "\n"
    "plt.plot(DD_ex, label='Discriminador'); plt.plot(GG_ex, label='Generador')\n"
    "plt.legend(); plt.title('GAN Balanceo Dinamico - Curvas'); plt.show()\n"
    "\n"
    "imgs_ex = gen_ex(np.random.normal(0,1,(10, lat_ex))).numpy()\n"
    "for i in range(5):\n"
    "    plt.subplot(2,5,i+1);   plt.imshow(imgs_ex[i,:,:,0],   cmap='gray'); plt.axis('off')\n"
    "    plt.subplot(2,5,5+i+1); plt.imshow(imgs_ex[2*i,:,:,0], cmap='gray'); plt.axis('off')\n"
    "plt.suptitle('GAN Balanceo Dinamico: imagenes generadas'); plt.tight_layout(); plt.show()\n"
)

# =====================================================================
# EJERCICIO EXTRA 2: Modelo integrado (CIFAR-10 + cGAN + DCGAN + Balanceo)
# =====================================================================
ej_extra2_code = (
    "# Ejercicio EXTRA 2: Modelo integrado\n"
    "# Combina: CIFAR-10 + etiquetas (cGAN) + capas convolucionales (DCGAN) + balanceo dinamico\n"
    "from keras.datasets import cifar10\n"
    "from keras.layers import (Input, Dense, Reshape, Flatten, BatchNormalization,\n"
    "                           LeakyReLU, Conv2D, Conv2DTranspose, Concatenate)\n"
    "from keras.models import Model\n"
    "from keras.optimizers import Adam\n"
    "import tensorflow as tf\n"
    "import numpy as np\n"
    "from tqdm.notebook import tqdm\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "# --- Parametros ---\n"
    "latent_int = 100; num_cls = 10; img_sh_int = (32, 32, 3)\n"
    "class_names = ['avion','auto','pajaro','gato','ciervo',\n"
    "               'perro','rana','caballo','barco','camion']\n"
    "\n"
    "# --- Datos CIFAR-10 con etiquetas ---\n"
    "(X_int, y_int_raw), (_, _) = cifar10.load_data()\n"
    "y_int = y_int_raw.flatten()\n"
    "X_int = X_int.astype(np.float32) / 255.0 * 2.0 - 1.0\n"
    "y_hot_int = np.eye(num_cls)[y_int]  # (50000, 10)\n"
    "\n"
    "# --- Generador convolucional condicional ---\n"
    "# noise (100,) + etiqueta (10,) => imagen (32,32,3)\n"
    "noise_i = Input(shape=(latent_int,), name='noise_int')\n"
    "label_i = Input(shape=(num_cls,), name='label_gen_int')\n"
    "x = Concatenate()([noise_i, label_i])\n"
    "x = Dense(4 * 4 * 256, activation='relu')(x)\n"
    "x = Reshape((4, 4, 256))(x)\n"
    "x = BatchNormalization(momentum=0.8)(x)\n"
    "x = Conv2DTranspose(128, 4, strides=2, padding='same')(x)  # 8x8\n"
    "x = LeakyReLU(0.2)(x); x = BatchNormalization(0.8)(x)\n"
    "x = Conv2DTranspose(64, 4, strides=2, padding='same')(x)   # 16x16\n"
    "x = LeakyReLU(0.2)(x); x = BatchNormalization(0.8)(x)\n"
    "x = Conv2DTranspose(32, 4, strides=2, padding='same')(x)   # 32x32\n"
    "x = LeakyReLU(0.2)(x); x = BatchNormalization(0.8)(x)\n"
    "x = Conv2D(3, 3, padding='same', activation='tanh')(x)     # 32x32x3\n"
    "int_gen = Model([noise_i, label_i], x, name='integrated_generator')\n"
    "int_gen.summary()\n"
    "\n"
    "# --- Discriminador convolucional condicional ---\n"
    "# La etiqueta se proyecta a un mapa espacial (32,32,10) y se concatena con la imagen\n"
    "img_i   = Input(shape=img_sh_int, name='image_int')\n"
    "label_d = Input(shape=(num_cls,), name='label_disc_int')\n"
    "lmap = Dense(32*32*num_cls)(label_d)\n"
    "lmap = Reshape((32, 32, num_cls))(lmap)\n"
    "xd = Concatenate()([img_i, lmap])              # (32,32,13)\n"
    "xd = Conv2D(64,  3, strides=2, padding='same')(xd); xd = LeakyReLU(0.2)(xd)  # 16x16\n"
    "xd = Conv2D(128, 3, strides=2, padding='same')(xd); xd = LeakyReLU(0.2)(xd)  # 8x8\n"
    "xd = Conv2D(256, 3, strides=2, padding='same')(xd); xd = LeakyReLU(0.2)(xd)  # 4x4\n"
    "xd = Flatten()(xd)\n"
    "xd = Dense(1, activation='sigmoid')(xd)\n"
    "int_disc = Model([img_i, label_d], xd, name='integrated_discriminator')\n"
    "int_disc.summary()\n"
    "int_disc.compile(loss='binary_crossentropy', optimizer=Adam(2e-4, beta_1=0.5), metrics=['accuracy'])\n"
    "\n"
    "# --- Modelo combinado ---\n"
    "int_disc.trainable = False\n"
    "n_in = Input(shape=(latent_int,)); l_in = Input(shape=(num_cls,))\n"
    "int_combined = Model([n_in, l_in],\n"
    "                     int_disc([int_gen([n_in, l_in]), l_in]),\n"
    "                     name='integrated_gan')\n"
    "int_combined.compile(loss='binary_crossentropy', optimizer=Adam(2e-4, beta_1=0.5))\n"
    "int_disc.trainable = True\n"
    "\n"
    "# --- Entrenamiento con balanceo dinamico ---\n"
    "n_sam_int = 10000; ep_int = 50; bs_int = 64\n"
    "base_bat_int = n_sam_int // bs_int\n"
    "DD_int, GG_int = [], []\n"
    "prev_di, prev_gi = 1.0, 1.0\n"
    "\n"
    "pb = tqdm(range(ep_int), desc='GAN Integrado')\n"
    "for epoch in pb:\n"
    "    ratio_i  = float(np.clip(prev_di / (prev_di + prev_gi + 1e-8), 0.2, 0.8))\n"
    "    n_d_i    = max(1, int(base_bat_int * ratio_i))\n"
    "    n_g_i    = max(1, int(base_bat_int * (1.0 - ratio_i)))\n"
    "    g_li, d_li, d_ai = 0.0, 0.0, 0.0\n"
    "\n"
    "    int_disc.trainable = True\n"
    "    for _ in range(n_d_i):\n"
    "        idx = np.random.choice(len(X_int), bs_int, replace=False)\n"
    "        xr = X_int[idx]; lr = y_hot_int[idx]\n"
    "        lf = np.eye(num_cls)[np.random.randint(0, num_cls, bs_int)]\n"
    "        xf = int_gen.predict([np.random.normal(0,1,(bs_int, latent_int)), lf], verbose=0)\n"
    "        dr = int_disc.train_on_batch([xr, lr], np.ones((bs_int,1)))\n"
    "        df = int_disc.train_on_batch([xf, lf], np.zeros((bs_int,1)))\n"
    "        d_li += 0.5*(dr[0]+df[0]); d_ai += 0.5*(dr[1]+df[1])\n"
    "    d_li /= n_d_i; d_ai /= n_d_i\n"
    "\n"
    "    int_disc.trainable = False\n"
    "    for _ in range(n_g_i):\n"
    "        n_v = np.random.normal(0,1,(bs_int, latent_int))\n"
    "        l_v = np.eye(num_cls)[np.random.randint(0, num_cls, bs_int)]\n"
    "        g_li += int_combined.train_on_batch([n_v, l_v], np.ones((bs_int,1)))\n"
    "    g_li /= n_g_i\n"
    "\n"
    "    prev_di = d_li; prev_gi = g_li\n"
    "    pb.set_description(f'd={n_d_i} g={n_g_i} | gen={g_li:.4f} disc={d_li:.4f} acc={d_ai:.4f}')\n"
    "    DD_int.append(d_li); GG_int.append(g_li)\n"
    "\n"
    "plt.plot(DD_int, label='Discriminador'); plt.plot(GG_int, label='Generador')\n"
    "plt.legend(); plt.title('GAN Integrado (CIFAR-10 + cGAN + DCGAN + Balanceo)'); plt.show()\n"
    "\n"
    "# Visualizar: real vs generada por clase\n"
    "fig, axes = plt.subplots(2, num_cls, figsize=(20, 4))\n"
    "for i in range(num_cls):\n"
    "    n_v = np.random.normal(0,1,(1, latent_int)); l_v = np.eye(num_cls)[[i]]\n"
    "    img_gen = int_gen.predict([n_v, l_v], verbose=0)[0]\n"
    "    img_gen = (img_gen + 1.0) / 2.0\n"
    "    idx_real = np.where(y_int == i)[0][0]\n"
    "    img_real = (X_int[idx_real] + 1.0) / 2.0\n"
    "    axes[0, i].imshow(img_real); axes[0, i].set_title(class_names[i]); axes[0, i].axis('off')\n"
    "    axes[1, i].imshow(img_gen);  axes[1, i].axis('off')\n"
    "axes[0, 0].set_ylabel('Real', fontsize=10)\n"
    "axes[1, 0].set_ylabel('Generada', fontsize=10)\n"
    "plt.suptitle('GAN Integrado - Real vs Generada por clase'); plt.tight_layout(); plt.show()\n"
)

# =====================================================================
# Localizar celdas e insertar en orden inverso
# =====================================================================
cells = nb['cells']

def find_cell(keyword):
    for i, c in enumerate(cells):
        src = c.get('source', '')
        if isinstance(src, list):
            src = ''.join(src)
        if keyword in src:
            return i
    return -1

idx_ej1    = find_cell('Ejercicio 1:\n')
idx_ej2    = find_cell('Ejercicio 2:\n')
idx_ej3    = find_cell('Ejercicio 3:\n')
extras     = [i for i, c in enumerate(cells)
              if 'Ejercicio EXTRA' in (''.join(c.get('source','')) if isinstance(c.get('source',''), list) else c.get('source',''))]
idx_extra1 = extras[0]
idx_extra2 = extras[1]

print(f"Ejercicio 1 en celda {idx_ej1}")
print(f"Ejercicio 2 en celda {idx_ej2}")
print(f"Ejercicio 3 en celda {idx_ej3}")
print(f"Extra 1    en celda {idx_extra1}")
print(f"Extra 2    en celda {idx_extra2}")

insertions = sorted([
    (idx_ej1,    ej1_code),
    (idx_ej2,    ej2_code),
    (idx_ej3,    ej3_code),
    (idx_extra1, ej_extra1_code),
    (idx_extra2, ej_extra2_code),
], key=lambda x: x[0], reverse=True)

for idx, src in insertions:
    cells.insert(idx + 1, code_cell(src))

with open('P4_parte_1_GANs.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"\nNotebook guardado. Total celdas: {len(nb['cells'])}")
