import json

with open('P4_parte_2_DMs.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

def code_cell(source):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source
    }

# =====================================================================
# EJERCICIO: Adaptar DDIM para MNIST (28x28 escala de grises)
# =====================================================================
dm_mnist_code = (
    "# Ejercicio: Adaptar el modelo DDIM para MNIST (digitos en escala de grises)\n"
    "#\n"
    "# Cambios principales respecto al codigo original de flores:\n"
    "# 1. Dataset: MNIST en vez de Oxford Flowers 102\n"
    "# 2. image_size: 28x28 (mantenemos la resolucion original de MNIST)\n"
    "# 3. Canales: 1 (escala de grises) en vez de 3 (RGB)\n"
    "# 4. Arquitectura mas pequena (widths mas estrechos) porque las imagenes son mas simples\n"
    "# 5. Normalizacion adaptada: MNIST ya esta en [0,1] tras /255\n"
    "\n"
    "import math\n"
    "import numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "import tensorflow as tf\n"
    "import keras\n"
    "from keras import layers\n"
    "from tensorflow.keras import ops\n"
    "\n"
    "# --- Hiperparametros para MNIST ---\n"
    "image_size_mnist    = 28\n"
    "num_channels_mnist  = 1       # escala de grises\n"
    "plot_diffusion_steps_mnist = 20\n"
    "\n"
    "# sampling\n"
    "min_signal_rate_m = 0.02\n"
    "max_signal_rate_m = 0.95\n"
    "\n"
    "# architecture (mas estrecha que la de flores)\n"
    "embedding_dims_m        = 32\n"
    "embedding_max_frequency_m = 1000.0\n"
    "widths_m    = [16, 32, 64]   # 3 niveles bastan para imagenes 28x28\n"
    "block_depth_m = 2\n"
    "\n"
    "# optimization\n"
    "batch_size_m  = 64\n"
    "ema_m         = 0.999\n"
    "learning_rate_m = 1e-3\n"
    "weight_decay_m  = 1e-4\n"
    "\n"
    "# --- Pipeline de datos MNIST ---\n"
    "(X_mnist_train, _), (X_mnist_test, _) = tf.keras.datasets.mnist.load_data()\n"
    "# Combinar train + test para tener mas datos y repetir\n"
    "X_all_mnist = np.concatenate([X_mnist_train, X_mnist_test], axis=0)  # (70000, 28, 28)\n"
    "X_all_mnist = X_all_mnist.astype(np.float32) / 255.0                 # [0, 1]\n"
    "X_all_mnist = np.expand_dims(X_all_mnist, -1)                        # (70000, 28, 28, 1)\n"
    "\n"
    "def prepare_mnist_dataset(data, val_split=0.2):\n"
    "    n_val = int(len(data) * val_split)\n"
    "    train_data = data[n_val:]\n"
    "    val_data   = data[:n_val]\n"
    "    def make_ds(arr):\n"
    "        return (tf.data.Dataset.from_tensor_slices(arr)\n"
    "                .cache()\n"
    "                .repeat(5)\n"
    "                .shuffle(10 * batch_size_m)\n"
    "                .batch(batch_size_m, drop_remainder=True)\n"
    "                .prefetch(tf.data.AUTOTUNE))\n"
    "    return make_ds(train_data), make_ds(val_data)\n"
    "\n"
    "train_dataset_m, val_dataset_m = prepare_mnist_dataset(X_all_mnist)\n"
    "print('Dataset MNIST listo. Ejemplo batch shape:', next(iter(train_dataset_m)).shape)\n"
    "\n"
    "# --- Red U-Net adaptada a 1 canal ---\n"
    "@keras.saving.register_keras_serializable()\n"
    "def sinusoidal_embedding_m(x):\n"
    "    embedding_min_frequency_m = 1.0\n"
    "    frequencies = ops.exp(\n"
    "        ops.linspace(\n"
    "            ops.log(embedding_min_frequency_m),\n"
    "            ops.log(embedding_max_frequency_m),\n"
    "            embedding_dims_m // 2,\n"
    "        )\n"
    "    )\n"
    "    angular_speeds = ops.cast(2.0 * math.pi * frequencies, 'float32')\n"
    "    embeddings = ops.concatenate(\n"
    "        [ops.sin(angular_speeds * x), ops.cos(angular_speeds * x)], axis=3\n"
    "    )\n"
    "    return embeddings\n"
    "\n"
    "def ResidualBlock_m(width):\n"
    "    def apply(x):\n"
    "        input_width = x.shape[3]\n"
    "        residual = x if input_width == width else layers.Conv2D(width, kernel_size=1)(x)\n"
    "        x = layers.BatchNormalization(center=False, scale=False)(x)\n"
    "        x = layers.Conv2D(width, kernel_size=3, padding='same', activation='swish')(x)\n"
    "        x = layers.Conv2D(width, kernel_size=3, padding='same')(x)\n"
    "        return layers.Add()([x, residual])\n"
    "    return apply\n"
    "\n"
    "def DownBlock_m(width, block_depth):\n"
    "    def apply(x):\n"
    "        x, skips = x\n"
    "        for _ in range(block_depth):\n"
    "            x = ResidualBlock_m(width)(x); skips.append(x)\n"
    "        x = layers.AveragePooling2D(pool_size=2)(x)\n"
    "        return x\n"
    "    return apply\n"
    "\n"
    "def UpBlock_m(width, block_depth):\n"
    "    def apply(x):\n"
    "        x, skips = x\n"
    "        x = layers.UpSampling2D(size=2, interpolation='bilinear')(x)\n"
    "        for _ in range(block_depth):\n"
    "            x = layers.Concatenate()([x, skips.pop()]); x = ResidualBlock_m(width)(x)\n"
    "        return x\n"
    "    return apply\n"
    "\n"
    "def get_network_mnist(image_size, widths, block_depth, num_channels=1):\n"
    "    noisy_images   = keras.Input(shape=(image_size, image_size, num_channels))\n"
    "    noise_variances = keras.Input(shape=(1, 1, 1))\n"
    "\n"
    "    e = layers.Lambda(sinusoidal_embedding_m,\n"
    "                      output_shape=(1, 1, embedding_dims_m))(noise_variances)\n"
    "    e = layers.UpSampling2D(size=image_size, interpolation='nearest')(e)\n"
    "\n"
    "    x = layers.Conv2D(widths[0], kernel_size=1)(noisy_images)\n"
    "    x = layers.Concatenate()([x, e])\n"
    "\n"
    "    skips = []\n"
    "    for width in widths[:-1]:\n"
    "        x = DownBlock_m(width, block_depth)([x, skips])\n"
    "    for _ in range(block_depth):\n"
    "        x = ResidualBlock_m(widths[-1])(x)\n"
    "    for width in reversed(widths[:-1]):\n"
    "        x = UpBlock_m(width, block_depth)([x, skips])\n"
    "\n"
    "    # Salida con num_channels canales (1 para MNIST)\n"
    "    x = layers.Conv2D(num_channels, kernel_size=1, kernel_initializer='zeros')(x)\n"
    "    return keras.Model([noisy_images, noise_variances], x, name='unet_mnist')\n"
    "\n"
    "# --- Modelo de difusion adaptado ---\n"
    "@keras.saving.register_keras_serializable()\n"
    "class DiffusionModelMNIST(keras.Model):\n"
    "    def __init__(self, image_size, widths, block_depth, num_channels=1):\n"
    "        super().__init__()\n"
    "        self.num_channels = num_channels\n"
    "        self.image_size   = image_size\n"
    "        self.normalizer   = layers.Normalization()\n"
    "        self.network      = get_network_mnist(image_size, widths, block_depth, num_channels)\n"
    "        self.ema_network  = keras.models.clone_model(self.network)\n"
    "\n"
    "    def compile(self, **kwargs):\n"
    "        super().compile(**kwargs)\n"
    "        self.noise_loss_tracker = keras.metrics.Mean(name='n_loss')\n"
    "        self.image_loss_tracker = keras.metrics.Mean(name='i_loss')\n"
    "\n"
    "    @property\n"
    "    def metrics(self):\n"
    "        return [self.noise_loss_tracker, self.image_loss_tracker]\n"
    "\n"
    "    def denormalize(self, images):\n"
    "        images = self.normalizer.mean + images * self.normalizer.variance**0.5\n"
    "        return ops.clip(images, 0.0, 1.0)\n"
    "\n"
    "    def diffusion_schedule(self, diffusion_times):\n"
    "        start_angle = ops.cast(ops.arccos(max_signal_rate_m), 'float32')\n"
    "        end_angle   = ops.cast(ops.arccos(min_signal_rate_m), 'float32')\n"
    "        angles      = start_angle + diffusion_times * (end_angle - start_angle)\n"
    "        return ops.sin(angles), ops.cos(angles)  # noise_rate, signal_rate\n"
    "\n"
    "    def denoise(self, noisy_images, noise_rates, signal_rates, training):\n"
    "        network = self.network if training else self.ema_network\n"
    "        pred_noises = network([noisy_images, noise_rates**2], training=training)\n"
    "        pred_images = (noisy_images - noise_rates * pred_noises) / signal_rates\n"
    "        return pred_noises, pred_images\n"
    "\n"
    "    def reverse_diffusion(self, initial_noise, diffusion_steps):\n"
    "        num_images = initial_noise.shape[0]\n"
    "        step_size  = 1.0 / diffusion_steps\n"
    "        next_noisy_images = initial_noise\n"
    "        for step in range(diffusion_steps):\n"
    "            noisy_images   = next_noisy_images\n"
    "            diffusion_times = ops.ones((num_images, 1, 1, 1)) - step * step_size\n"
    "            noise_rates, signal_rates = self.diffusion_schedule(diffusion_times)\n"
    "            pred_noises, pred_images  = self.denoise(\n"
    "                noisy_images, noise_rates, signal_rates, training=False)\n"
    "            next_diffusion_times = diffusion_times - step_size\n"
    "            next_noise_rates, next_signal_rates = self.diffusion_schedule(next_diffusion_times)\n"
    "            next_noisy_images = (next_signal_rates * pred_images +\n"
    "                                 next_noise_rates  * pred_noises)\n"
    "        return pred_images\n"
    "\n"
    "    def generate(self, num_images, diffusion_steps):\n"
    "        initial_noise   = keras.random.normal(\n"
    "            shape=(num_images, self.image_size, self.image_size, self.num_channels))\n"
    "        generated_images = self.reverse_diffusion(initial_noise, diffusion_steps)\n"
    "        return self.denormalize(generated_images)\n"
    "\n"
    "    def train_step(self, images):\n"
    "        images = self.normalizer(images, training=True)\n"
    "        noises = keras.random.normal(\n"
    "            shape=(batch_size_m, self.image_size, self.image_size, self.num_channels))\n"
    "        diffusion_times = keras.random.uniform(\n"
    "            shape=(batch_size_m, 1, 1, 1), minval=0.0, maxval=1.0)\n"
    "        noise_rates, signal_rates = self.diffusion_schedule(diffusion_times)\n"
    "        noisy_images = signal_rates * images + noise_rates * noises\n"
    "        with tf.GradientTape() as tape:\n"
    "            pred_noises, pred_images = self.denoise(\n"
    "                noisy_images, noise_rates, signal_rates, training=True)\n"
    "            noise_loss = self.loss(noises, pred_noises)\n"
    "            image_loss = self.loss(images, pred_images)\n"
    "        gradients = tape.gradient(noise_loss, self.network.trainable_weights)\n"
    "        self.optimizer.apply_gradients(zip(gradients, self.network.trainable_weights))\n"
    "        self.noise_loss_tracker.update_state(noise_loss)\n"
    "        self.image_loss_tracker.update_state(image_loss)\n"
    "        for w, ew in zip(self.network.weights, self.ema_network.weights):\n"
    "            ew.assign(ema_m * ew + (1 - ema_m) * w)\n"
    "        return {m.name: m.result() for m in self.metrics}\n"
    "\n"
    "    def test_step(self, images):\n"
    "        images = self.normalizer(images, training=False)\n"
    "        noises = keras.random.normal(\n"
    "            shape=(batch_size_m, self.image_size, self.image_size, self.num_channels))\n"
    "        diffusion_times = keras.random.uniform(\n"
    "            shape=(batch_size_m, 1, 1, 1), minval=0.0, maxval=1.0)\n"
    "        noise_rates, signal_rates = self.diffusion_schedule(diffusion_times)\n"
    "        noisy_images = signal_rates * images + noise_rates * noises\n"
    "        pred_noises, pred_images = self.denoise(\n"
    "            noisy_images, noise_rates, signal_rates, training=False)\n"
    "        self.noise_loss_tracker.update_state(self.loss(noises, pred_noises))\n"
    "        self.image_loss_tracker.update_state(self.loss(images, pred_images))\n"
    "        return {m.name: m.result() for m in self.metrics}\n"
    "\n"
    "    def plot_images(self, epoch=None, logs=None, num_rows=3, num_cols=6):\n"
    "        generated = self.generate(\n"
    "            num_images=num_rows * num_cols,\n"
    "            diffusion_steps=plot_diffusion_steps_mnist)\n"
    "        plt.figure(figsize=(num_cols * 2.0, num_rows * 2.0))\n"
    "        for row in range(num_rows):\n"
    "            for col in range(num_cols):\n"
    "                idx = row * num_cols + col\n"
    "                plt.subplot(num_rows, num_cols, idx + 1)\n"
    "                plt.imshow(generated[idx, :, :, 0], cmap='gray')\n"
    "                plt.axis('off')\n"
    "        plt.tight_layout(); plt.show(); plt.close()\n"
    "\n"
    "# --- Compilar y entrenar ---\n"
    "model_mnist = DiffusionModelMNIST(image_size_mnist, widths_m, block_depth_m,\n"
    "                                   num_channels=num_channels_mnist)\n"
    "model_mnist.compile(\n"
    "    optimizer=keras.optimizers.AdamW(learning_rate=learning_rate_m,\n"
    "                                     weight_decay=weight_decay_m),\n"
    "    loss=keras.losses.mean_absolute_error,\n"
    ")\n"
    "model_mnist.normalizer.adapt(train_dataset_m)\n"
    "\n"
    "num_epochs_mnist = 10  # aumentar a 50+ para mejores resultados\n"
    "hist_mnist = model_mnist.fit(\n"
    "    train_dataset_m,\n"
    "    epochs=num_epochs_mnist,\n"
    "    validation_data=val_dataset_m,\n"
    "    callbacks=[keras.callbacks.LambdaCallback(on_epoch_end=model_mnist.plot_images)],\n"
    ")\n"
    "\n"
    "# --- Generar digitos al final ---\n"
    "model_mnist.plot_images()\n"
    "\n"
    "# Mostrar curvas de entrenamiento\n"
    "plt.plot(hist_mnist.history['n_loss'], label='n_loss train')\n"
    "plt.plot(hist_mnist.history['val_n_loss'], label='n_loss val')\n"
    "plt.legend(); plt.title('DDIM MNIST - Curvas de entrenamiento'); plt.show()\n"
)

# =====================================================================
# Localizar celda del ejercicio e insertar despues de ella
# =====================================================================
cells = nb['cells']

def find_cell(keyword):
    for i, c in enumerate(cells):
        src = c.get('source', '')
        if isinstance(src, list):
            src = ''.join(src)
        if keyword in src:
            return i
    return -1

idx_ej = find_cell('Ejercicios')
print(f"Seccion Ejercicios encontrada en celda {idx_ej}")
# El ejercicio real (la descripcion) esta en la siguiente celda
idx_ej_desc = find_cell('funcione con MNIST')
print(f"Descripcion del ejercicio MNIST en celda {idx_ej_desc}")

if idx_ej_desc >= 0:
    cells.insert(idx_ej_desc + 1, {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": dm_mnist_code
    })
    print("Celda de codigo insertada correctamente.")
else:
    print("ERROR: no se encontro la celda del ejercicio.")

with open('P4_parte_2_DMs.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"Notebook DMs guardado. Total celdas: {len(nb['cells'])}")
